#123 オンライン開催向けのパス追加
afes-website/docs pull request #127
Opened 2020-09-25 10:21 UTC by su8ru

close #123 

とりあえず draft
ご指摘お待ちしております

2020-09-25 10:59 UTC, Takeno-hito requested changes
commentをつかうんだったらcommentを追加できるようにしてほしいかな

2020-09-25 11:02 UTC, Takeno-hito commented on src/apis/exh/content/draft/index.ts
> +    resBody: Draft[];
queryなくていいの？

2020-09-25 11:19 UTC, Takeno-hito submitted a review, later dismissed

2020-09-25 12:33 UTC, ibuki2003 requested changes
おまたせ
- `exh/{id}/content/` のがよくないですか(他パスも同様)
  - exhはprefixなのか そしたら`exh/exhibitions/{id}`とか(contentを文章のそれだと思っていた)
- パスに出てくるオブジェクト名は複数形でおねがいします。

2020-09-25 12:33 UTC, ibuki2003 commented on src/apis/exh/content/draft/@types.ts
> +  author: UserInfo;
これはadminが送信するかも、の意図ですか? ふつうexh userが自分のものを送信するだけな気がする
それともexh_idがないところを見るとこれが展示idですか? それなら`exh_id: string;`が適切そう

2020-09-25 12:33 UTC, ibuki2003 commented on src/apis/exh/content/draft/@types.ts
> +export type NewDraft = Pick<Draft, "content" | "comments">;
commentできるpathがあるのにnewにてcommentsが渡せる必要はないのでは、と思いました

2020-09-25 12:33 UTC, ibuki2003 commented on src/apis/exh/content/draft/@types.ts
> +export type DraftStatus = "waiting" | "accepted" | "rejected" | "published";
(accept/rejectとpublishを一括管理するの違う気がする(Slackで言わなかったのは、ごめんね))
published、ここで管理する意図が見えないです

2020-09-25 12:33 UTC, ibuki2003 commented on src/apis/exh/content/draft/_id@number.ts/index.ts
> +   * draft を編集する
draft編集、いる? (投げなおしでよくないか)
それかwaitingのみ とコメントしておくか

2020-09-25 12:33 UTC, ibuki2003 commented on src/apis/exh/content/draft/_id@number.ts/publish/index.ts
> +   * draft を公開し、status を publish にする
```suggestion
   * draft を公開し、status を published にする
```

先のれびゅーの方針とぶつかるけど、一応…

2020-09-25 12:33 UTC, ibuki2003 commented on src/apis/exh/content/draft/index.ts
> +   * - blogAdmin : 全ての draft
箇条書きのkeyとvalueが逆のがよさそう
それか「見えるdraft」とするか

2020-09-25 12:33 UTC, ibuki2003 commented on src/apis/exh/content/draft/index.ts
> +   * 400: パラメータに過不足がある
余計なものがあってもエラーにはならない (言葉の綾なんだろうけど、気になる)
```suggestion
   * 400: 不正なパラメータ
```

2020-09-25 22:52 UTC, su8ru commented on src/apis/exh/content/draft/@types.ts
> +export type DraftStatus = "waiting" | "accepted" | "rejected" | "published";
下書きの状態としてはこの 4 つで正しい気がする
もう公開した下書きがいつまでも accepted として残り続けるのは違うじゃん

2020-09-26 04:42 UTC, su8ru commented on src/apis/exh/content/draft/_id@number.ts/index.ts
> +   * draft を編集する
admin の使用を想定している節があり…

2020-09-26 04:52 UTC, su8ru commented on src/apis/exh/content/draft/index.ts
> +   * 400: パラメータに過不足がある
`パラメータに不備がある` で統一されてるっぽい

2020-09-26 05:01 UTC, su8ru commented on src/apis/exh/content/draft/index.ts
> +   * - blogAdmin : 全ての draft
他と統一してこんな感じでいかがでしょう

```
   * @remarks
   * 必要な権限:
   * - exh : 自身が作成した draft のみ取得可能
   * - blogAdmin : 全ての draft を取得可能
```

2020-09-26 05:26 UTC, su8ru commented on src/apis/exh/content/draft/_id@number.ts/index.ts
> +   * draft を編集する
post は exh_id を指定できないので
してもいいけど、exh が exh_id を指定したりとかいろいろめんどくさそう

2020-09-26 05:28 UTC, su8ru commented on src/apis/exh/content/draft/@types.ts
> +export type DraftStatus = "waiting" | "accepted" | "rejected" | "published";
あ、ソフトデリートするんだっけ？結局この辺がどう帰着したのかわかんない

2020-09-26 12:05 UTC, Takeno-hito commented on src/apis/exh/content/draft/@types.ts
> +export type DraftStatus = "waiting" | "accepted" | "rejected" | "published";
Revisionと同じ運用はだめなんだっけ

2020-09-26 12:05 UTC, Takeno-hito commented on src/apis/exh/content/draft/@types.ts
> +export type DraftStatus = "waiting" | "accepted" | "rejected" | "published";
Publishedあってもいいとはおもいます

2020-09-26 12:05 UTC, Takeno-hito approved these changes

2020-09-26 12:06 UTC, su8ru commented on src/apis/exh/content/draft/@types.ts
> +export type DraftStatus = "waiting" | "accepted" | "rejected" | "published";
exh table から draft id を参照するってこと？

2020-09-26 13:19 UTC, Takeno-hito commented on src/apis/exh/content/draft/@types.ts
> +export type DraftStatus = "waiting" | "accepted" | "rejected" | "published";
Backはそれでいいでしょ

2020-09-27 08:02 UTC, ibuki2003 approved these changes

2020-09-27 08:02 UTC, Takeno-hito approved these changes

2020-09-27 08:03 UTC, merged