Exhibitionを指定させるように
afes-website/docs pull request #243
Opened 2021-04-28 06:31 UTC by Takeno-hito

resolve: #242

2021-04-28 12:33 UTC, su8ru requested changes

2021-04-28 12:33 UTC, su8ru commented on src/apis/guests/_id@string/enter/index.ts
> +   * * @remarks
なんか明らかにおかしくないか

2021-04-28 12:33 UTC, su8ru commented on src/apis/guests/_id@string/exit/index.ts
> +   * admin権限がない場合 exhibition_id には実行ユーザーの Id を指定しなければならない
```suggestion
   * admin 権限がない場合 exhibition_id には実行ユーザーの id を指定しなければならない
```

2021-04-28 12:33 UTC, su8ru commented on src/apis/guests/_id@string/enter/index.ts
> +    reqBody: { exhibition_id: string };
exhibition_id?: string じゃなんかだめなんだっけ？

2021-04-28 12:37 UTC, Takeno-hito commented on src/apis/guests/_id@string/enter/index.ts
> +    reqBody: { exhibition_id: string };
え、指定しといた方がわかりやすくない？
adminの時は必須になる

2021-04-28 12:42 UTC, ibuki2003 commented on src/apis/guests/_id@string/enter/index.ts
> +    reqBody: { exhibition_id: string };
省略可にしないならいいけど(全員必須でもいい気はするよね docも書きなおしになるけど) そうでないなら`?`はいると思います

2021-04-28 14:05 UTC, su8ru requested changes

2021-04-28 14:05 UTC, su8ru commented on src/apis/guests/_id@string/enter/index.ts
> +   * admin権限がない場合 exhibition_id には実行ユーザーの Id を指定しなければならない
日本語どうにかして
```suggestion
   * admin 権限がない場合 exhibition_id には実行ユーザーの Id を指定しなければならない
```

2021-04-28 14:05 UTC, su8ru commented on src/apis/guests/_id@string/enter/index.ts
> +   * 403: これを実行する権限がない または 自身以外の exhibition_id を指定する権限がない
「これ」がなにを指しているのか不明瞭

2021-04-28 14:11 UTC, Takeno-hito commented on src/apis/guests/_id@string/enter/index.ts
> +    reqBody: { exhibition_id: string };
省略不可にするほいう方針でいいですか

2021-04-28 14:30 UTC, su8ru commented on src/apis/guests/_id@string/enter/index.ts
> +    reqBody: { exhibition_id: string };
いいんじゃないですか

2021-04-29 09:33 UTC, su8ru commented on src/apis/guests/_id@string/enter/index.ts
> +   * admin権限がない場合 exhibition_id には実行ユーザーの Id を指定しなければならない
```
exhibition 権限の場合、exhibition_id は実行ユーザーの id と同一である必要がある
```
とか？

2021-04-29 09:35 UTC, su8ru commented on src/apis/guests/_id@string/enter/index.ts
> +   * 403: これを実行する権限がない または 自身以外の exhibition_id を指定する権限がない
```
403: 権限不足（exhibition 権限で実行ユーザー以外の exhibition_id を指定した場合を含む）
```

とか…？あんまりよくないかも

2021-04-29 10:40 UTC, Takeno-hito commented on src/apis/guests/_id@string/enter/index.ts
> +   * admin権限がない場合 exhibition_id には実行ユーザーの Id を指定しなければならない
Exhibition and Admin という権限パターンなどの存在が許されているので Exh の場合 とは書きたくないという気持ちがあります

2021-04-29 10:42 UTC, Takeno-hito commented on src/apis/guests/_id@string/enter/index.ts
> +   * 403: これを実行する権限がない または 自身以外の exhibition_id を指定する権限がない
実はAPIの仕様として403の時もstatus codeを付けるべきなのでは？それがベストっぽそう 作業範囲が広がるから別prが立つことにはなるけど

2021-05-08 05:18 UTC, su8ru approved these changes

2021-05-08 05:18 UTC, ibuki2003 approved these changes

2021-05-08 05:19 UTC, merged