#269 ユーザー管理・エンドポイント変更
afes-website/docs pull request #272
Opened 2021-08-29 12:58 UTC by su8ru

#269

2021-08-29 23:08 UTC, ibuki2003 requested changes
throws 403の有無ってなんか意味ある? どっちかに統一したさが

2021-08-29 23:08 UTC, ibuki2003 commented on src/apis/auth/users/_id@string/regenerate/index.ts
> +   * セッション鍵を再生成する
ログインしているセッションをすべて無効化する、くらいは書いたほうがよさそう
あとはadminが自分自身で叩いたときの挙動は特に例外なし？

2021-08-29 23:08 UTC, ibuki2003 commented on src/apis/auth/users/index.ts
> +   * @returns ログイン中のユーザー情報
嘘

2021-08-30 03:14 UTC, su8ru commented
> throws 403の有無ってなんか意味ある? どっちかに統一したさが
@ibuki2003 

throws 403 は、権限場合分けがあるときに書かれてるイメージがある（ので私はそうした）

2021-08-30 03:16 UTC, su8ru commented on src/apis/auth/users/_id@string/regenerate/index.ts
> +   * セッション鍵を再生成する
admin が自分で叩いたときもセッション無効化でいいと思う

2021-08-30 08:13 UTC, ibuki2003 approved these changes

2021-08-30 09:24 UTC, merged