#287 [v3.4.0] bulk update を追加
afes-website/docs pull request #294
Opened 2021-10-22 09:32 UTC by Takeno-hito

2021-10-31 14:56 UTC, ibuki2003 requested changes

2021-10-31 14:56 UTC, ibuki2003 commented on src/apis/guests/bulk-update/@types.ts
> +export type BulkQuery = {
タイムスタンプ

2021-10-31 14:56 UTC, ibuki2003 commented on src/apis/guests/bulk-update/index.ts
> +   * @remarks
- logにしか記録されないこと
- 整合性は(検証できないので)無視されること
- 定義されたcodeが受け付けない理由になることあるっけ？
  →http codeみたいな返し方のが楽なのでは…？ 404か403か200

2021-10-31 14:56 UTC, ibuki2003 commented on src/apis/guests/bulk-update/index.ts
> +   * @returns 来場者に関する情報
ちがうとおもいます

2021-11-02 11:48 UTC, Takeno-hito commented on src/apis/guests/bulk-update/index.ts
> +   * @remarks
ExhibitionNotFound, GuestAlreadyCheckedIn (DB重複が起きる), check-out時の AlreadyCheckedOut (どうしようもない) とかかな… ログを残すだけ残すやつら

2021-11-09 16:21 UTC, Takeno-hito commented
we wanna review

2021-11-09 16:23 UTC, su8ru requested changes

2021-11-09 16:23 UTC, su8ru commented on src/apis/guests/bulk-update/index.ts
> +   * | その他              | 各パスの対応表を参照                       |
おい

2021-11-09 16:31 UTC, su8ru commented on src/apis/guests/bulk-update/index.ts
> +   * 各エントリについて順に、状態を再現するように可能な限り処理される。
各エントリについて順に←要る？実装上の問題では
状態を再現するように← timestamp を元に、くらい書いてもいい気がします
可能な限り←致命的な問題がない限り

2021-11-11 00:37 UTC, su8ru commented on src/apis/guests/bulk-update/@types.ts
> +  is_applied: boolean;
is_ok みたいなノリのほうがやりやすいという結論に至らなかったっけ

2021-11-11 00:37 UTC, su8ru commented
はやくりりーすしたいです（app がなんもできん）

2021-11-11 00:55 UTC, ibuki2003 commented on src/apis/guests/bulk-update/index.ts
> +   * 各エントリについて順に、状態を再現するように可能な限り処理される。
順に: mapくらいの感覚でいた 処理順というより返答順

2021-11-11 00:57 UTC, su8ru commented on src/apis/guests/bulk-update/index.ts
> +   * 各エントリについて順に、状態を再現するように可能な限り処理される。
処理文脈感が強いから、返答順は `@returns` におまかせ

2021-11-11 07:03 UTC, ibuki2003 approved these changes

2021-11-11 09:43 UTC, su8ru approved these changes

2021-11-11 10:29 UTC, merged